/* DashPoint game skin roster — unlock rules mirror the source file names */
window.DashPointShopSkinCats = [
  { id: "food", label: "FOOD" },
  { id: "faces", label: "FACES" },
  { id: "animals", label: "ANIMALS" },
  { id: "nature", label: "NATURE" },
  { id: "memes", label: "MEMES" },
  { id: "luxury", label: "LUXURY" },
  { id: "countries", label: "COUNTRIES" },
  { id: "misc", label: "MISCELLANEOUS" },
];
window.DashPointSkins = [
  { id: 1, name: "Cube", src: "assets/skins/skin-1.png" },
  { id: 2, name: "Plus", src: "assets/skins/skin-2.png" },
  { id: 3, name: "Blank", src: "assets/skins/skin-3.png" },
  { id: 4, name: "Arrow", src: "assets/skins/skin-4.png" },
  { id: 5, name: "Bob", src: "assets/skins/skin-5.png" },
  { id: 6, name: "Happy Circle", src: "assets/skins/skin-6.png", hint: "Die 20 times", unlock: { type: "deaths", n: 20 } },
  { id: 7, name: "Mess", src: "assets/skins/skin-7.png", hint: "Die 5 times", unlock: { type: "deaths", n: 5 } },
  { id: 8, name: "Modern Art Be Like", src: "assets/skins/skin-8.png", hint: "Die for the first time", unlock: { type: "deaths", n: 1 } },
  { id: 9, name: "TLTN", src: "assets/skins/skin-9.png", hint: "Beat any level", unlock: { type: "beat" } },
  { id: 10, name: "Triangle", src: "assets/skins/skin-10.png", hint: "Die 40 times", unlock: { type: "deaths", n: 40 } },
  { id: 11, name: "TRUEBOBSKIN", src: "assets/skins/skin-11.png", hint: "Press Alt+A in this menu", unlock: { type: "secreta" } },
  { id: 12, name: "Goofy", src: "assets/skins/skin-12.png", hint: "Die 100 times", unlock: { type: "deaths", n: 100 } },
  { id: 13, name: "Triple T", src: "assets/skins/skin-13.png", hint: "Die 1000 times", unlock: { type: "deaths", n: 1000 } },
  { id: 14, name: "Gucci Morty", src: "assets/skins/skin-14.png", hint: "Jump 100 times", unlock: { type: "jumps", n: 100 } },
  { id: 15, name: "please touch grass", src: "assets/skins/skin-15.png", hint: "Jump 5000 times or die 4000 times", unlock: { type: "either", jumps: 5000, deaths: 4000 } },
  { id: 16, name: "mogity", src: "assets/skins/skin-16.png", hint: "Buy in the shop", shopCat: "faces", unlock: { type: "shop", cost: 500 } },
  { id: 17, name: "I love DP", src: "assets/skins/skin-17.png", hint: "Buy in the shop", shopCat: "misc", unlock: { type: "shop", cost: 1000 } },
  { id: 18, name: "rich", src: "assets/skins/skin-18.png", hint: "Buy in the shop", shopCat: "luxury", unlock: { type: "shop", cost: 10000 } },
  { id: 19, name: "i'm with a noob", src: "assets/skins/skin-19.png", hint: "Redeem a code", unlock: { type: "code" } },
  { id: 20, name: "burger", src: "assets/skins/skin-20.png", hint: "Redeem a code", unlock: { type: "code" } },
  { id: 21, name: "Torture Face", src: "assets/skins/skin-21.png", hint: "Beat any Torture level", unlock: { type: "diff", n: 5 } },
  { id: 22, name: "the moon", src: "assets/skins/skin-22.png", hint: "Buy for 100 coins or die 50 times", shopCat: "nature", unlock: { type: "shop", cost: 100, deaths: 50 } },
  { id: 23, name: "a orange orange", src: "assets/skins/skin-23.png", hint: "Buy in the shop", shopCat: "food", unlock: { type: "shop", cost: 100 } },
  { id: 24, name: "apple", src: "assets/skins/skin-24.png", hint: "Buy in the shop", shopCat: "food", unlock: { type: "shop", cost: 100 } },
  { id: 25, name: "banana skin", src: "assets/skins/skin-25.png", hint: "Buy in the shop", shopCat: "food", unlock: { type: "shop", cost: 200 } },
  { id: 26, name: "ramen", src: "assets/skins/skin-26.png", hint: "Buy in the shop", shopCat: "food", unlock: { type: "shop", cost: 500 } },
  { id: 27, name: "Donut", src: "assets/skins/skin-27.png", hint: "Buy in the shop", shopCat: "food", unlock: { type: "shop", cost: 300 } },
  { id: 28, name: "invisible", src: "assets/skins/skin-28.png", hint: "Jump 5000 times", unlock: { type: "jumps", n: 5000 } },
  { id: 29, name: "Cool", src: "assets/skins/skin-29.png", hint: "Buy in the shop or redeem a code", shopCat: "faces", unlock: { type: "shop", cost: 1000000000 } },
  { id: 30, name: "The Cat", src: "assets/skins/skin-30.png", hint: "Buy in the shop", shopCat: "animals", unlock: { type: "shop", cost: 100000000000 } },
  { id: 31, name: "Golden Tripple T", src: "assets/skins/skin-31.png", hint: "Buy in the shop", shopCat: "luxury", unlock: { type: "shop", cost: 1000000000000 } },
  { id: 32, name: "Glacier", src: "assets/skins/skin-32.png", hint: "Buy in the shop", shopCat: "nature", unlock: { type: "shop", cost: 2500 }, anim: { src: "assets/skins/skin-32-strip.png", frames: 4, fps: 6 } },
  { id: 33, name: "Magma", src: "assets/skins/skin-33.png", hint: "Buy in the shop", shopCat: "nature", unlock: { type: "shop", cost: 5000 }, anim: { src: "assets/skins/skin-33-strip.png", frames: 4, fps: 8 } },
  { id: 34, name: "Slime", src: "assets/skins/skin-34.png", hint: "Die 200 times", unlock: { type: "deaths", n: 200 }, anim: { src: "assets/skins/skin-34-strip.png", frames: 4, fps: 6 } },
  { id: 35, name: "Discord", src: "assets/skins/skin-35.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-35-strip.png", frames: 4, fps: 4 } },
  { id: 36, name: "RGB", src: "assets/skins/skin-36.gif", hint: "Buy in the shop", shopCat: "luxury", unlock: { type: "shop", cost: "100000000000000" } },
  { id: 37, name: "Rubik", src: "assets/skins/skin-37.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-37-strip.png", frames: 4, fps: 3 } },
  { id: 38, name: "Static", src: "assets/skins/skin-38.png", hint: "Die 777 times", unlock: { type: "deaths", n: 777 }, anim: { src: "assets/skins/skin-38-strip.png", frames: 4, fps: 10 } },
  { id: 39, name: "Netanyahu", src: "assets/skins/skin-39.png", hint: "Redeem a code", unlock: { type: "code" }, irl: true },
  { id: 40, name: "Putin", src: "assets/skins/skin-40.png", hint: "Redeem a code", unlock: { type: "code" }, irl: true },
  { id: 41, name: "Trump", src: "assets/skins/skin-41.png", hint: "Redeem a code", unlock: { type: "code" }, irl: true },
  { id: 42, name: "6 7", src: "assets/skins/skin-42.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-42-strip.png", frames: 4, fps: 6 } },
  { id: 43, name: "Skibidi Toilet", src: "assets/skins/skin-43.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-43-strip.png", frames: 4, fps: 6 } },
  { id: 44, name: "Trollface", src: "assets/skins/skin-44.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-44-strip.png", frames: 4, fps: 6 } },
  { id: 45, name: "Doge", src: "assets/skins/skin-45.png", hint: "Buy in the shop", shopCat: "memes", unlock: { type: "shop", cost: 13370 }, anim: { src: "assets/skins/skin-45-strip.png", frames: 4, fps: 4 } },
  { id: 46, name: "Among Us", src: "assets/skins/skin-46.png", hint: "Redeem a code", unlock: { type: "code" }, anim: { src: "assets/skins/skin-46-strip.png", frames: 4, fps: 6 } },
  { id: 47, name: "Nyan Cat", src: "assets/skins/skin-47.png", hint: "Buy in the shop", shopCat: "memes", unlock: { type: "shop", cost: 30000 }, anim: { src: "assets/skins/skin-47-strip.png", frames: 4, fps: 8 } },
  { id: 48, name: "shocked", src: "assets/skins/skin-48.png", hint: "Buy in the shop", shopCat: "faces", unlock: { type: "shop", cost: 100000 } },
  { id: 49, name: "Wink", src: "assets/skins/skin-49.gif", hint: "Buy in the shop", shopCat: "faces", unlock: { type: "shop", cost: 100000000000 } },
  { id: 50, name: "cursed", src: "assets/skins/skin-50.png", hint: "Buy in the shop", shopCat: "luxury", unlock: { type: "shop", cost: "1000000000000000" } },
  { id: 51, name: "isreal", src: "assets/skins/skin-51.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 52, name: "Belerus", src: "assets/skins/skin-52.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 53, name: "Afghanistan", src: "assets/skins/skin-53.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 54, name: "Albania", src: "assets/skins/skin-54.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 55, name: "Algeria", src: "assets/skins/skin-55.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 56, name: "Andorra", src: "assets/skins/skin-56.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 57, name: "Angola", src: "assets/skins/skin-57.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 58, name: "Argentina", src: "assets/skins/skin-58.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 59, name: "Armenia", src: "assets/skins/skin-59.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 60, name: "Australia", src: "assets/skins/skin-60.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 61, name: "Austria", src: "assets/skins/skin-61.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 62, name: "Azerbaijan", src: "assets/skins/skin-62.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 63, name: "Bahamas", src: "assets/skins/skin-63.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 64, name: "Bahrain", src: "assets/skins/skin-64.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 65, name: "Bangladesh", src: "assets/skins/skin-65.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 66, name: "Barbados", src: "assets/skins/skin-66.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 67, name: "Belgium", src: "assets/skins/skin-67.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 68, name: "Belize", src: "assets/skins/skin-68.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 69, name: "Benin", src: "assets/skins/skin-69.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 70, name: "Bhutan", src: "assets/skins/skin-70.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 71, name: "Bolivia", src: "assets/skins/skin-71.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 72, name: "Bosnia and Herzegovina", src: "assets/skins/skin-72.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 73, name: "Botswana", src: "assets/skins/skin-73.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 74, name: "Brazil", src: "assets/skins/skin-74.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 75, name: "Brunei", src: "assets/skins/skin-75.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 76, name: "Bulgaria", src: "assets/skins/skin-76.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 77, name: "Burkina Faso", src: "assets/skins/skin-77.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 78, name: "Burundi", src: "assets/skins/skin-78.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 79, name: "Cambodia", src: "assets/skins/skin-79.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 80, name: "Cameroon", src: "assets/skins/skin-80.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 81, name: "Canada", src: "assets/skins/skin-81.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 82, name: "Cape Verde", src: "assets/skins/skin-82.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 83, name: "Central African Republic", src: "assets/skins/skin-83.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 84, name: "Chad", src: "assets/skins/skin-84.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 85, name: "Chile", src: "assets/skins/skin-85.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 86, name: "China", src: "assets/skins/skin-86.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 87, name: "Colombia", src: "assets/skins/skin-87.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 88, name: "Comoros", src: "assets/skins/skin-88.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 89, name: "Congo", src: "assets/skins/skin-89.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 90, name: "Costa Rica", src: "assets/skins/skin-90.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 91, name: "Croatia", src: "assets/skins/skin-91.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 92, name: "Cuba", src: "assets/skins/skin-92.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 93, name: "Cyprus", src: "assets/skins/skin-93.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 94, name: "Czechia", src: "assets/skins/skin-94.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 95, name: "Denmark", src: "assets/skins/skin-95.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 96, name: "Djibouti", src: "assets/skins/skin-96.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 97, name: "Dominica", src: "assets/skins/skin-97.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 98, name: "Dominican Republic", src: "assets/skins/skin-98.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 99, name: "DR Congo", src: "assets/skins/skin-99.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 100, name: "Ecuador", src: "assets/skins/skin-100.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 101, name: "Egypt", src: "assets/skins/skin-101.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 102, name: "El Salvador", src: "assets/skins/skin-102.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 103, name: "Equatorial Guinea", src: "assets/skins/skin-103.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 104, name: "Eritrea", src: "assets/skins/skin-104.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 105, name: "Estonia", src: "assets/skins/skin-105.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 106, name: "Eswatini", src: "assets/skins/skin-106.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 107, name: "Ethiopia", src: "assets/skins/skin-107.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 108, name: "Fiji", src: "assets/skins/skin-108.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 109, name: "Finland", src: "assets/skins/skin-109.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 110, name: "France", src: "assets/skins/skin-110.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 111, name: "Gabon", src: "assets/skins/skin-111.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 112, name: "Gambia", src: "assets/skins/skin-112.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 113, name: "Georgia", src: "assets/skins/skin-113.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 114, name: "Germany", src: "assets/skins/skin-114.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 115, name: "Ghana", src: "assets/skins/skin-115.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 116, name: "Greece", src: "assets/skins/skin-116.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 117, name: "Grenada", src: "assets/skins/skin-117.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 118, name: "Guatemala", src: "assets/skins/skin-118.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 119, name: "Guinea", src: "assets/skins/skin-119.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 120, name: "Guinea-Bissau", src: "assets/skins/skin-120.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 121, name: "Guyana", src: "assets/skins/skin-121.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 122, name: "Haiti", src: "assets/skins/skin-122.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 123, name: "Honduras", src: "assets/skins/skin-123.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 124, name: "Hungary", src: "assets/skins/skin-124.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 125, name: "Iceland", src: "assets/skins/skin-125.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 126, name: "India", src: "assets/skins/skin-126.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 127, name: "Indonesia", src: "assets/skins/skin-127.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 128, name: "Iran", src: "assets/skins/skin-128.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 129, name: "Iraq", src: "assets/skins/skin-129.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 130, name: "Ireland", src: "assets/skins/skin-130.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 131, name: "Italy", src: "assets/skins/skin-131.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 132, name: "Ivory Coast", src: "assets/skins/skin-132.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 133, name: "Jamaica", src: "assets/skins/skin-133.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 134, name: "Japan", src: "assets/skins/skin-134.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 135, name: "Jordan", src: "assets/skins/skin-135.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 136, name: "Kazakhstan", src: "assets/skins/skin-136.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 137, name: "Kenya", src: "assets/skins/skin-137.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 138, name: "Kiribati", src: "assets/skins/skin-138.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 139, name: "Kosovo", src: "assets/skins/skin-139.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 140, name: "Kuwait", src: "assets/skins/skin-140.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 141, name: "Kyrgyzstan", src: "assets/skins/skin-141.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 142, name: "Laos", src: "assets/skins/skin-142.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 143, name: "Latvia", src: "assets/skins/skin-143.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 144, name: "Lebanon", src: "assets/skins/skin-144.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 145, name: "Lesotho", src: "assets/skins/skin-145.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 146, name: "Liberia", src: "assets/skins/skin-146.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 147, name: "Libya", src: "assets/skins/skin-147.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 148, name: "Liechtenstein", src: "assets/skins/skin-148.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 149, name: "Lithuania", src: "assets/skins/skin-149.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 150, name: "Luxembourg", src: "assets/skins/skin-150.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 151, name: "Madagascar", src: "assets/skins/skin-151.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 152, name: "Malawi", src: "assets/skins/skin-152.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 153, name: "Malaysia", src: "assets/skins/skin-153.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 154, name: "Maldives", src: "assets/skins/skin-154.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 155, name: "Mali", src: "assets/skins/skin-155.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 156, name: "Malta", src: "assets/skins/skin-156.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 157, name: "Marshall Islands", src: "assets/skins/skin-157.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 158, name: "Mauritania", src: "assets/skins/skin-158.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 159, name: "Mauritius", src: "assets/skins/skin-159.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 160, name: "Mexico", src: "assets/skins/skin-160.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 161, name: "Micronesia", src: "assets/skins/skin-161.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 162, name: "Moldova", src: "assets/skins/skin-162.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 163, name: "Monaco", src: "assets/skins/skin-163.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 164, name: "Mongolia", src: "assets/skins/skin-164.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 165, name: "Montenegro", src: "assets/skins/skin-165.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 166, name: "Morocco", src: "assets/skins/skin-166.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 167, name: "Mozambique", src: "assets/skins/skin-167.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 168, name: "Myanmar", src: "assets/skins/skin-168.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 169, name: "Namibia", src: "assets/skins/skin-169.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 170, name: "Nauru", src: "assets/skins/skin-170.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 171, name: "Nepal", src: "assets/skins/skin-171.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 172, name: "Netherlands", src: "assets/skins/skin-172.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 173, name: "New Zealand", src: "assets/skins/skin-173.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 174, name: "Nicaragua", src: "assets/skins/skin-174.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 175, name: "Niger", src: "assets/skins/skin-175.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 176, name: "Nigeria", src: "assets/skins/skin-176.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 177, name: "North Korea", src: "assets/skins/skin-177.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 178, name: "North Macedonia", src: "assets/skins/skin-178.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 179, name: "Norway", src: "assets/skins/skin-179.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 180, name: "Oman", src: "assets/skins/skin-180.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 181, name: "Pakistan", src: "assets/skins/skin-181.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 182, name: "Palau", src: "assets/skins/skin-182.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 183, name: "Palestine", src: "assets/skins/skin-183.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 184, name: "Panama", src: "assets/skins/skin-184.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 185, name: "Papua New Guinea", src: "assets/skins/skin-185.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 186, name: "Paraguay", src: "assets/skins/skin-186.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 187, name: "Peru", src: "assets/skins/skin-187.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 188, name: "Philippines", src: "assets/skins/skin-188.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 189, name: "Poland", src: "assets/skins/skin-189.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 190, name: "Portugal", src: "assets/skins/skin-190.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 191, name: "Qatar", src: "assets/skins/skin-191.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 192, name: "Romania", src: "assets/skins/skin-192.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 193, name: "Russia", src: "assets/skins/skin-193.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 194, name: "Rwanda", src: "assets/skins/skin-194.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 195, name: "Samoa", src: "assets/skins/skin-195.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 196, name: "San Marino", src: "assets/skins/skin-196.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 197, name: "Sao Tome and Principe", src: "assets/skins/skin-197.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 198, name: "Saudi Arabia", src: "assets/skins/skin-198.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 199, name: "Senegal", src: "assets/skins/skin-199.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 200, name: "Serbia", src: "assets/skins/skin-200.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 201, name: "Seychelles", src: "assets/skins/skin-201.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 202, name: "Sierra Leone", src: "assets/skins/skin-202.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 203, name: "Singapore", src: "assets/skins/skin-203.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 204, name: "Slovakia", src: "assets/skins/skin-204.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 205, name: "Slovenia", src: "assets/skins/skin-205.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 206, name: "Solomon Islands", src: "assets/skins/skin-206.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 207, name: "Somalia", src: "assets/skins/skin-207.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 208, name: "South Africa", src: "assets/skins/skin-208.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 209, name: "South Korea", src: "assets/skins/skin-209.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 210, name: "South Sudan", src: "assets/skins/skin-210.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 211, name: "Spain", src: "assets/skins/skin-211.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 212, name: "Sri Lanka", src: "assets/skins/skin-212.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 213, name: "Sudan", src: "assets/skins/skin-213.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 214, name: "Suriname", src: "assets/skins/skin-214.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 215, name: "Sweden", src: "assets/skins/skin-215.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 216, name: "Switzerland", src: "assets/skins/skin-216.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 217, name: "Syria", src: "assets/skins/skin-217.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 218, name: "Taiwan", src: "assets/skins/skin-218.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 219, name: "Tajikistan", src: "assets/skins/skin-219.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 220, name: "Tanzania", src: "assets/skins/skin-220.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 221, name: "Thailand", src: "assets/skins/skin-221.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 222, name: "Timor-Leste", src: "assets/skins/skin-222.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 223, name: "Togo", src: "assets/skins/skin-223.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 224, name: "Tonga", src: "assets/skins/skin-224.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 225, name: "Trinidad and Tobago", src: "assets/skins/skin-225.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 226, name: "Tunisia", src: "assets/skins/skin-226.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 227, name: "Turkey", src: "assets/skins/skin-227.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 228, name: "Turkmenistan", src: "assets/skins/skin-228.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 229, name: "Tuvalu", src: "assets/skins/skin-229.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 230, name: "Uganda", src: "assets/skins/skin-230.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 231, name: "Ukraine", src: "assets/skins/skin-231.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 232, name: "United Arab Emirates", src: "assets/skins/skin-232.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 233, name: "United Kingdom", src: "assets/skins/skin-233.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 234, name: "United States", src: "assets/skins/skin-234.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 235, name: "Uruguay", src: "assets/skins/skin-235.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 236, name: "Uzbekistan", src: "assets/skins/skin-236.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 237, name: "Vanuatu", src: "assets/skins/skin-237.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 238, name: "Vatican City", src: "assets/skins/skin-238.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 239, name: "Venezuela", src: "assets/skins/skin-239.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 240, name: "Vietnam", src: "assets/skins/skin-240.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 241, name: "Yemen", src: "assets/skins/skin-241.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 242, name: "Zambia", src: "assets/skins/skin-242.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
  { id: 243, name: "Zimbabwe", src: "assets/skins/skin-243.png", hint: "Buy in the shop", shopCat: "countries", unlock: { type: "shop", cost: 100 } },
];
