import http from "node:http";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)));
const port = Number(process.env.PORT || 5500);
const host = "127.0.0.1";
const mime = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".png": "image/png",
  ".json": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".m4a": "audio/mp4",
  ".mp3": "audio/mpeg",
  ".ogg": "audio/ogg",
};

function levelsDir() {
  const titled = path.join(root, "Levels");
  const lower = path.join(root, "levels");
  if (fs.existsSync(titled)) return titled;
  if (fs.existsSync(lower)) return lower;
  return titled;
}

function rebuildLevels() {
  const dir = levelsDir();
  if (!fs.existsSync(dir)) return;
  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json")).sort();
  const entries = [];
  for (const f of files) {
    try {
      entries.push({ file: f, json: JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")) });
    } catch (e) {
      console.warn("skipping", f, e.message);
    }
  }
  const out =
    "/* generated by serve.mjs / levels/build-levels.mjs — run it again after adding levels */\n" +
    "window.DashPointLevelData = " + JSON.stringify(entries) + ";\n";
  fs.writeFileSync(path.join(root, "js", "levels-data.js"), out);
  console.log("bundled", entries.length, "levels:", files.join(", "));
}

rebuildLevels();

const server = http.createServer((req, res) => {
  const url = decodeURIComponent((req.url || "/").split("?")[0]);
  let rel = url === "/" ? "index.html" : url.replace(/^\/+/, "");
  if (rel === "js/levels-data.js") rebuildLevels();
  if (/^levels\//i.test(rel)) {
    const mapped = path.join(levelsDir(), rel.replace(/^levels\//i, ""));
    if (fs.existsSync(mapped)) rel = path.relative(root, mapped).replace(/\\/g, "/");
  }
  const file = path.resolve(root, rel);
  if (file !== root && !file.startsWith(root + path.sep)) {
    res.writeHead(403);
    res.end("forbidden");
    return;
  }
  fs.readFile(file, (err, data) => {
    if (err) {
      res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("not found");
      return;
    }
    res.writeHead(200, { "Content-Type": mime[path.extname(file)] || "application/octet-stream" });
    res.end(data);
  });
});

server.listen(port, host, () => {
  console.log("DashPoint game: http://" + host + ":" + port + "/");
});
