import { readdirSync, readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = dirname(fileURLToPath(import.meta.url));
const files = readdirSync(root).filter((f) => f.endsWith(".json")).sort();
const entries = [];
for (const f of files) {
  try {
    const data = JSON.parse(readFileSync(join(root, f), "utf8"));
    entries.push({ file: f, json: data });
  } catch (e) {
    console.warn("skipping", f, e.message);
  }
}
const out =
  "/* generated by levels/build-levels.mjs — run it again after adding levels */\n" +
  "window.DashPointLevelData = " + JSON.stringify(entries) + ";\n";
writeFileSync(join(dirname(root), "js", "levels-data.js"), out);
console.log("bundled", entries.length, "levels:", files.join(", "));
